# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: v-aprozo

steps:
- task: 91443475-df55-4874-944b-39253b558790@0
  inputs:
    sshEndpoint: 'vscale'
    runOptions: 'inline'
    inline: 'ps aux'
    readyTimeout: '20000'
