trigger:
- master

pool: v-aprozo

steps: 
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'src/*.tar.gz'
    destinationFolder: 'src/extract'
    cleanDestinationFolder: false

- task: NodeJsExec@0
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    script: 'throw "error";'