trigger:
- master

pool: v-aprozo
steps:
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'archives/*.zip'
    destinationFolder: 'files/'
    cleanDestinationFolder: false
  
- task: CmdLine@2
  inputs:
    script: |
      archive1=./files/archive1.txt
      archive2=./files/archive2.txt
      if [ ! -e "$archive1" ]; then
          exit 1
      if [ -e "$archive2" ]; then
          exit 1