trigger:
- master

pool: v-aprozo
steps:
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'archives/*.zip'
    destinationFolder: 'files/'
    cleanDestinationFolder: false
  
- task: CmdLine@2
  inputs:
    script: |
      file=./files/archive1.txt
      if [ ! -e "$file" ]; then
          echo "File does not exist"
      else 
          echo "File exists"
      fi